---
# Configure your freshly installed software
- hosts: all
  roles:
  - role: osxc.repository
    clone_url: https://github.com/robbyrussell/oh-my-zsh.git
    dest: /Users/{{ ansible_user_id }}/.oh-my-zsh
  - role: osxc.repository
    clone_url: https://github.com/square/maximum-awesome.git
    dest: /Users/{{ ansible_user_id }}/.vim
    links:
    - src: vimrc
      dest: /Users/{{ ansible_user_id }}/.vimrc
    - src: vimrc.bundles
      dest: /Users/{{ ansible_user_id }}/.vimrc.bundles
    - src: tmux.conf
      dest: /Users/{{ ansible_user_id }}/.tmux.conf
  - role: osxc.repository
    clone_url: https://github.com/gmarik/vundle.git
    dest: /Users/{{ ansible_user_id }}/.vim/bundle/vundle
  post_tasks:
  - copy: src=dotfiles/zshrc dest=/Users/{{ ansible_user_id }}/.zshrc backup=yes
  - copy: src=dotfiles/vimrc.local dest=/Users/{{ ansible_user_id }}/.vimrc.local backup=yes
  - copy: src=dotfiles/vimrc.bundles.local dest=/Users/{{ ansible_user_id }}/.vimrc.bundles.local backup=yes
  - copy: src=dotfiles/tmux.conf.local dest=/Users/{{ ansible_user_id }}/.tmux.conf.local backup=yes

- hosts: all
  roles:
  - osxc.common-env
